name: comments

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]

jobs:
  comments:

    runs-on: ubuntu-latest

    steps:
    - uses: sobolevn/restrict-cursing-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
